workflows:
  version: 2
  build:
    jobs:
      - node-v8
      - node-v9:
          requires:
            - node-v8
      - node-v10:
          requires:
            - node-v9

version: 2
jobs:
  node-base: &node-base
    docker:
      - image: node
    steps:
      - run:
          name: Versions
          command: npm version
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Lint
          command: npm run lint
      - run:
          name: Test
          command: npm test
      - run:
          name: Compile
          command: npm run compile
      - run:
          name: Startup server
          command: |
            wget https://saucelabs.com/downloads/sc-4.4.12-linux.tar.gz
            tar -xzf sc-4.4.12-linux.tar.gz
      - run:
          name: Start SauceLabs Tunnel
          command: npm start & wait-on http://localhost:9900
          background: true
      - run:
          name: Integration
          command: npm run cypress-ci
  node-v8:
    <<: *node-base
    docker:
      - image: node:8
  node-v9:
    <<: *node-base
    docker:
      - image: node:9
  node-v10:
    <<: *node-base
    docker:
      - image: node:10