workflows:
  version: 2
  build:
    jobs:
      - node-v8
      - node-v10:
          requires:
            - node-v8

version: 2
jobs:
  node-base: &node-base
    docker:
      - image: cypress/base
        environment:
          TERM: xterm
    steps:
      - run:
          name: Versions
          command: npm version
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Lint
          command: npm run lint
      - run:
          name: Test
          command: npm test
      - run:
          name: Compile
          command: npm run compile
      - run:
          name: Starting server
          command: npm start
          background: true
      - run:
          name: Integration
          command: npm run cypress-ci
  node-v8:
    <<: *node-base
    docker:
      - image: cypress/base:8
  node-v10:
    <<: *node-base
    docker:
      - image: cypress/base:10